apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-dev-project
  namespace: argocd
spec: 
  destination: 
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/pilotgab/argocd-file.git"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true