apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/pilotgab/argocd-file.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true